### ISSUE TITLE
HTTP git remotes are not correctly parsed, breaking HTML links

### ISSUE THREAD

**Issue by SimonMarquis** [square/invert#13]
This weirdly written function (looks like an automated translation from another language) does not correctly parse HTTP git remotes:

https://github.com/square/invert/blob/935a9aae5177dc7cdf16aceb8934425a367f695e/invert-gradle-plugin/src/main/kotlin/com/squareup/invert/internal/GitDataCollector.kt#L27-L47

For instance,

```bash
❯ git remote get-url origin
https://github.com/foo/bar.git
```
will lead to this function returning `https://https///github.com/foo/bar`, which then is written like this in the header (and also used in multiple other places like git branch, git commit, etc.):

```html
<a href="https://https///github.com/foo/bar" target="_blank">//github.com/foo/bar</a>
```

Let me know if you accept PRs at this stage of the project :)

**Comment by handstandsam** [comment]
I just fixed this (and wrote my first test for that part of the codebase!) https://github.com/square/invert/commit/6c17f45ee10863609b3891ec969389efb9c30516

Great minds think alike!

It should be in the latest snapshot of `0.0.2-dev00-SNAPSHOT`.  Sorry about the long version names.  Trying to start publish more, but trying to convey that it's very much a work in progress.

I'm closing this as it's "fixed".  Let me know if you have any more issues and I can re-open.

**Comment by handstandsam** [comment]
I verified this morning that the fix worked!  Note: I have it linking to an exact commit now instead of a branch.  I think that's more accurate, but it's debatable about user experience.  I created https://github.com/square/invert/issues/16 to capture discussion on that topic if you have any input.  Thanks again!
