### ISSUE TITLE
Could not resolve - 0.0.1-dev-SNAPSHOT

### ISSUE THREAD

**Issue by Veeresh8** [square/invert#5]
This is my Gradle file, after sync I'm not able to resolve the plugin and throws an error - 

**Plugin [id: 'com.squareup.invert', version: '0.0.1-dev-SNAPSHOT'] was not found in any of the following sources:**

Although I've added the maven source links.

    buildscript {

    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://oss.sonatype.org/service/local/repositories/snapshots/content" }
    }

    dependencies {
        classpath 'com.android.tools:r8:8.0.40' //https://github.com/google/dagger/issues/2291 & https://issuetracker.google.com/issues/178045782#comment5
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.48.1'
        classpath 'com.android.tools.build:bundletool:0.9.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.6'
       }
    }

    plugins {
        id "io.sentry.android.gradle" version "3.0.0-beta.3"
        id "org.sonarqube" version "3.4.0.2513"
        id "com.squareup.invert" version "0.0.1-dev-SNAPSHOT"
    }
 
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://maven.google.com" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url 'https://oss.jfrog.org/artifactory/oss-snapshot-local' }
        maven { url "https://jitpack.io" }
        maven { url "https://sdk.smartlook.com/android/release" }
        maven { url 'https://maven.fpregistry.io/releases' }
        maven { url "https://oss.sonatype.org/service/local/repositories/snapshots/content" }
         }

      }

    apply from: 'common/dependencies.gradle'

    tasks.register('clean', Delete) {
        delete rootProject.buildDir
    }

Let me know what should be changed to resolve this

**Comment by handstandsam** [comment]
It looks like you also need to add **s01**
```
maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots" } // SNAPSHOT Versions
```

That should do it.  https://central.sonatype.org/publish/publish-guide/#deployment
```
Note: As of February 2021, all new projects began being provisioned on https://s01.oss.sonatype.org/. If your project is not provisioned on https://s01.oss.sonatype.org/, you will want to login to the legacy host https://oss.sonatype.org/.
```

**Comment by Veeresh8** [comment]
hello @handstandsam I still face the same error even after pointing to **s01**

**Plugin [id: 'com.squareup.invert', version: '0.0.1-dev-SNAPSHOT'] was not found in any of the following sources:**

**Comment by handstandsam** [comment]
@Veeresh8 - `0.0.1-dev` is now on Maven Central.  Hopefully that'll work for you!
